export const DSA_PROBLEMS_FULL = [
  {
    id: 'p1',
    title: 'Two Sum',
    difficulty: 'Easy',
    topic: 'Arrays',
    companies: ['Google', 'Amazon', 'Microsoft'],
    description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
    examples: JSON.stringify([{ input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'nums[0] + nums[1] == 9' }]),
    constraints: ['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9'],
    expected_output: '[0, 1]',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/two-sum'
  },
  {
    id: 'p2',
    title: 'Add Two Numbers',
    difficulty: 'Medium',
    topic: 'Linked List',
    companies: ['Amazon', 'Microsoft'],
    description: 'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order.',
    examples: JSON.stringify([{ input: 'l1 = [2,4,3], l2 = [5,6,4]', output: '[7,0,8]', explanation: '342 + 465 = 807' }]),
    constraints: ['Node count in range [1, 100]', '0 <= Node.val <= 9'],
    expected_output: '[7, 0, 8]',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/add-two-numbers'
  },
  {
    id: 'p3',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    topic: 'Strings',
    companies: ['Google', 'Adobe'],
    description: 'Given a string s, find the length of the longest substring without repeating characters.',
    examples: JSON.stringify([{ input: 's = "abcabcbb"', output: '3', explanation: 'The answer is "abc", with the length of 3.' }]),
    constraints: ['0 <= s.length <= 5 * 10^4'],
    expected_output: '3',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters'
  },
  {
    id: 'p4',
    title: 'Median of Two Sorted Arrays',
    difficulty: 'Hard',
    topic: 'Binary Search',
    companies: ['Google', 'Goldman Sachs'],
    description: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.',
    examples: JSON.stringify([{ input: 'nums1 = [1,3], nums2 = [2]', output: '2.00000', explanation: 'merged array = [1,2,3] and median is 2.' }]),
    constraints: ['nums1.length == m', 'nums2.length == n', '0 <= m <= 1000'],
    expected_output: '2.0',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/median-of-two-sorted-arrays'
  },
  {
    id: 'p5',
    title: 'Longest Palindromic Substring',
    difficulty: 'Medium',
    topic: 'Dynamic Programming',
    companies: ['Microsoft', 'Amazon'],
    description: 'Given a string s, return the longest palindromic substring in s.',
    examples: JSON.stringify([{ input: 's = "babad"', output: '"bab"', explanation: '"aba" is also a valid answer.' }]),
    constraints: ['1 <= s.length <= 1000'],
    expected_output: 'bab',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/longest-palindromic-substring'
  },
  {
    id: 'p6',
    title: 'Container With Most Water',
    difficulty: 'Medium',
    topic: 'Two Pointer',
    companies: ['Google', 'Uber'],
    description: 'Find two lines that together with x-axis forms a container containing the most water.',
    examples: JSON.stringify([{ input: 'height = [1,8,6,2,5,4,8,3,7]', output: '49', explanation: 'The max area of water is 49.' }]),
    constraints: ['n == height.length', '2 <= n <= 10^5'],
    expected_output: '49',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/container-with-most-water'
  },
  {
    id: 'p7',
    title: 'Trapping Rain Water',
    difficulty: 'Hard',
    topic: 'Two Pointer',
    companies: ['Amazon', 'Google'],
    description: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    examples: JSON.stringify([{ input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6', explanation: '6 units of rain water trapped.' }]),
    constraints: ['n == height.length', '1 <= n <= 2 * 10^4'],
    expected_output: '6',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/trapping-rain-water'
  },
  {
    id: 'p8',
    title: 'Merge K Sorted Lists',
    difficulty: 'Hard',
    topic: 'Heap',
    companies: ['Google', 'Microsoft'],
    description: 'You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list.',
    examples: JSON.stringify([{ input: 'lists = [[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]', explanation: 'merged linked list' }]),
    constraints: ['k == lists.length', '0 <= k <= 10^4'],
    expected_output: '[1,1,2,3,4,4,5,6]',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/merge-k-sorted-lists'
  },
  {
    id: 'p9',
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    topic: 'Stacks',
    companies: ['Amazon', 'Microsoft', 'Google'],
    description: 'Given a string s containing just the characters parentheses, determine if the input string is valid.',
    examples: JSON.stringify([{ input: 's = "()[]{}"', output: 'true', explanation: 'valid brackets' }]),
    constraints: ['1 <= s.length <= 10^4'],
    expected_output: 'true',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/valid-parentheses'
  },
  {
    id: 'p10',
    title: 'Subarray Sum Equals K',
    difficulty: 'Medium',
    topic: 'HashMap',
    companies: ['Google', 'Facebook'],
    description: 'Given an array of integers nums and an integer k, return the total number of subarrays whose sum equals to k.',
    examples: JSON.stringify([{ input: 'nums = [1,1,1], k = 2', output: '2', explanation: 'subarrays [1,1] count = 2' }]),
    constraints: ['1 <= nums.length <= 2 * 10^4'],
    expected_output: '2',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/subarray-sum-equals-k'
  },
  {
    id: 'p11',
    title: 'LRU Cache',
    difficulty: 'Hard',
    topic: 'System Design',
    companies: ['Google', 'Amazon', 'Microsoft'],
    description: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.',
    examples: JSON.stringify([{ input: '["LRUCache", "put", "put", "get"]', output: '[null, null, null, 1]', explanation: 'LRU cache simulation' }]),
    constraints: ['1 <= capacity <= 3000'],
    expected_output: '1',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/lru-cache'
  },
  {
    id: 'p12',
    title: 'Word Search',
    difficulty: 'Medium',
    topic: 'Backtracking',
    companies: ['Amazon', 'Microsoft'],
    description: 'Given an m x n grid of characters board and a string word, return true if word exists in the grid.',
    examples: JSON.stringify([{ input: 'board = [["A","B","C","E"]], word = "ABCCED"', output: 'true', explanation: 'word exists in board' }]),
    constraints: ['m == board.length', 'n == board[i].length'],
    expected_output: 'true',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/word-search'
  },
  {
    id: 'p13',
    title: 'Binary Tree Level Order Traversal',
    difficulty: 'Medium',
    topic: 'Trees',
    companies: ['Amazon', 'Microsoft'],
    description: 'Given the root of a binary tree, return the level order traversal of its nodes values.',
    examples: JSON.stringify([{ input: 'root = [3,9,20,null,null,15,7]', output: '[[3],[9,20],[15,7]]', explanation: 'level order traversal' }]),
    constraints: ['Node count in range [0, 2000]'],
    expected_output: '[[3],[9,20],[15,7]]',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/binary-tree-level-order-traversal'
  },
  {
    id: 'p14',
    title: 'Number of Islands',
    difficulty: 'Medium',
    topic: 'Graphs',
    companies: ['Amazon', 'Google', 'Microsoft'],
    description: 'Given an m x n 2D binary grid grid which represents a map of 1s (land) and 0s (water), return the number of islands.',
    examples: JSON.stringify([{ input: 'grid = [["1","1","0"],["1","1","0"],["0","0","1"]]', output: '2', explanation: '2 distinct islands' }]),
    constraints: ['m == grid.length', 'n == grid[i].length'],
    expected_output: '2',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/number-of-islands'
  },
  {
    id: 'p15',
    title: 'Coin Change',
    difficulty: 'Medium',
    topic: 'Dynamic Programming',
    companies: ['Amazon', 'Goldman Sachs'],
    description: 'Return the fewest number of coins that you need to make up that amount.',
    examples: JSON.stringify([{ input: 'coins = [1,2,5], amount = 11', output: '3', explanation: '11 = 5 + 5 + 1' }]),
    constraints: ['1 <= coins.length <= 12'],
    expected_output: '3',
    platform: 'LeetCode',
    platform_url: 'https://leetcode.com/problems/coin-change'
  }
];

export const COMPANIES_FULL = [
  {
    id: '1', name: 'Google', logo: 'G', tier: 'S', domain: 'Technology', ctc_range: '40-60 LPA',
    roles: ['SWE', 'SWE-II'], oa_pattern: ['DSA Heavy', '2-3 coding problems', '90 min'],
    interview_rounds: ['Online Assessment', 'Technical x3', 'Googliness Round'],
    topics_required: ['Graphs', 'DP', 'Trees', 'System Design', 'Arrays'],
    recently_asked: ['LRU Cache', 'Word Ladder', 'Meeting Rooms II', 'Merge K Sorted Lists'],
    readiness_score: 58, probability: 35, deadline: '2025-03-15', drive_date: '2025-03-20',
    locations: ['Bengaluru', 'Hyderabad'], hiring_status: 'upcoming',
    tips: ['Focus on System Design', 'Practice Google-specific behavioral questions'],
    projects_preferred: ['Distributed Systems', 'ML Projects'], skills: ['Java', 'C++', 'Python', 'Go']
  },
  {
    id: '2', name: 'Microsoft', logo: 'M', tier: 'S', domain: 'Technology', ctc_range: '35-50 LPA',
    roles: ['SWE', 'PM'], oa_pattern: ['Behavioral + Coding', '2 problems', '75 min'],
    interview_rounds: ['Online Assessment', 'Technical x2', 'HR Round'],
    topics_required: ['Arrays', 'Strings', 'Trees', 'OOP', 'OS'],
    recently_asked: ['Clone Graph', 'Binary Tree Zigzag', 'Design HashMap'],
    readiness_score: 72, probability: 52, deadline: '2025-02-28', drive_date: '2025-03-05',
    locations: ['Hyderabad', 'Noida', 'Bengaluru'], hiring_status: 'active',
    tips: ['Strong OOP concepts', 'Microsoft behavioral culture fit important'],
    projects_preferred: ['Cloud Projects', 'Enterprise Software'], skills: ['C#', 'C++', 'Python']
  },
  {
    id: '3', name: 'Amazon', logo: 'A', tier: 'S', domain: 'E-commerce/Cloud', ctc_range: '30-45 LPA',
    roles: ['SDE-I', 'SDE-II'], oa_pattern: ['Coding + Debugging', '2 problems', '90 min'],
    interview_rounds: ['OA', 'Technical x2', 'Bar Raiser', 'HR'],
    topics_required: ['Arrays', 'Strings', 'Trees', 'Graphs', 'DP', 'System Design'],
    recently_asked: ['Count Subarrays', 'Min Cost to Connect', 'LFU Cache'],
    readiness_score: 78, probability: 65, deadline: '2025-01-31', drive_date: '2025-02-20',
    locations: ['Bengaluru', 'Hyderabad', 'Chennai', 'Pune'], hiring_status: 'active',
    tips: ['Know all 16 Leadership Principles', 'STAR format for all answers'],
    projects_preferred: ['Microservices', 'AWS Projects'], skills: ['Java', 'Python', 'JavaScript']
  },
  {
    id: '4', name: 'Adobe', logo: 'Ad', tier: 'A', domain: 'Creative Software', ctc_range: '20-35 LPA',
    roles: ['SDE-I', 'Research Engineer'], oa_pattern: ['Coding', '3 problems', '120 min'],
    interview_rounds: ['OA', 'Technical x3', 'HR'],
    topics_required: ['Graphs', 'DP', 'Segment Trees', 'Trees', 'Strings'],
    recently_asked: ['Paint Board', 'Segment Tree Problems', 'Graph Coloring'],
    readiness_score: 82, probability: 72, deadline: '2025-02-10', drive_date: '2025-02-15',
    locations: ['Noida', 'Bengaluru'], hiring_status: 'upcoming',
    tips: ['Segment Tree questions common', 'Good problem solving skills'],
    projects_preferred: ['Image Processing', 'Creative Tools'], skills: ['C++', 'Java', 'Python']
  },
  {
    id: '5', name: 'Goldman Sachs', logo: 'GS', tier: 'A', domain: 'Finance/Tech', ctc_range: '25-40 LPA',
    roles: ['Analyst SDE', 'Quant Analyst'], oa_pattern: ['Math + Coding + CS', '120 min'],
    interview_rounds: ['OA', 'Technical x3', 'HR Round'],
    topics_required: ['Math', 'DP', 'Graphs', 'Probability', 'Puzzles'],
    recently_asked: ['High Five', 'Robot Bounded in Circle', 'Median of Arrays'],
    readiness_score: 64, probability: 48, deadline: '2025-03-01', drive_date: '2025-03-10',
    locations: ['Bengaluru'], hiring_status: 'active',
    tips: ['Probability and Math questions expected', 'Strong algorithms foundation'],
    projects_preferred: ['FinTech Apps', 'High Frequency Systems'], skills: ['C++', 'Java', 'Python']
  }
];
